FROM node:latest
RUN mkdir -p /usr/src/klnet.owner.report
WORKDIR /usr/src/klnet.owner.report
COPY java/jdk-14.0.2_linux-x64_bin.tar.gz /usr/local/jdk/
RUN tar -zxf /usr/local/jdk/jdk-14.0.2_linux-x64_bin.tar.gz -C /usr/local/jdk/
ENV JAVA_HOME="/usr/local/jdk/jdk-14.0.2"
ENV PATH $PATH:$JAVA_HOME/bin
COPY package.json ./
RUN yarn install
RUN apt-get update && apt-get install -y libaio1
ENV LD_LIBRARY_PATH="/usr/local/jdk/jdk-14.0.2/lib/server"
COPY . .
EXPOSE 5007
CMD ["node","server"]
